### ISSUE TITLE
Image Pull and run fails 

### ISSUE THREAD

**Issue by Jsyro** [decentralized-identity/uni-resolver-driver-did-sov#4] opened 2021-04-28 21:43 UTC
When running docker-compose up on this file.
```
version: "3.5"
networks:
  default:
    name: universal-resolver
services:
  driver-did-sov:
    image: universalresolver/driver-did-sov
    environment:
      uniresolver_driver_did_sov_libIndyPath:
      uniresolver_driver_did_sov_poolConfigs: "_;./local/localhost_9000.txn"
      uniresolver_driver_did_sov_poolVersions: _;2;
      uniresolver_driver_did_sov_walletName: wallet
    ports:
      - "7776:8080"
    volumes:
      - ./:/opt/driver-did-sov/local
```
The containers errors on startup with the following error. 
```
Attaching to resolver_driver-did-sov_1
driver-did-sov_1  | WARNING: An illegal reflective access operation has occurred
driver-did-sov_1  | WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
driver-did-sov_1  | WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
driver-did-sov_1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
driver-did-sov_1  | WARNING: All illegal access operations will be denied in a future release
driver-did-sov_1  | [INFO] Scanning for projects...
driver-did-sov_1  | Downloading from sovrin: https://repo.sovrin.org/repository/maven-public/decentralized-identity/uni-resolver/0.3-SNAPSHOT/maven-metadata.xml
driver-did-sov_1  | Downloading from danubetech-maven-public: https://repo.danubetech.com/repository/maven-public/decentralized-identity/uni-resolver/0.3-SNAPSHOT/maven-metadata.xml
Downloaded from danubetech-maven-public: https://repo.danubetech.com/repository/maven-public/decentralized-identity/uni-resolver/0.3-SNAPSHOT/maven-metadata.xml (611 B at 641 B/s)
driver-did-sov_1  | Downloading from danubetech-maven-public: https://repo.danubetech.com/repository/maven-public/decentralized-identity/uni-resolver/0.3-SNAPSHOT/uni-resolver-0.3-20210423.161953-110.pom
Downloaded from danubetech-maven-public: https://repo.danubetech.com/repository/maven-public/decentralized-identity/uni-resolver/0.3-SNAPSHOT/uni-resolver-0.3-20210423.161953-110.pom (11 kB at 23 kB/s)
driver-did-sov_1  | [ERROR] [ERROR] Some problems were encountered while processing the POMs:
driver-did-sov_1  | [ERROR] 'dependencies.dependency.version' for io.leonard:base58:jar must be a valid version but is '${io.leonard-base58.version}'. @ line 134, column 13
driver-did-sov_1  |  @ 
driver-did-sov_1  | [ERROR] The build could not read 1 project -> [Help 1]
driver-did-sov_1  | [ERROR]   
driver-did-sov_1  | [ERROR]   The project decentralized-identity:uni-resolver-driver-did-sov:0.3-SNAPSHOT (/opt/driver-did-sov/pom.xml) has 1 error
driver-did-sov_1  | [ERROR]     'dependencies.dependency.version' for io.leonard:base58:jar must be a valid version but is '${io.leonard-base58.version}'. @ line 134, column 13
driver-did-sov_1  | [ERROR] 
driver-did-sov_1  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
driver-did-sov_1  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
driver-did-sov_1  | [ERROR] 
driver-did-sov_1  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
driver-did-sov_1  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

**Comment by etschelp** [comment] 2021-04-29 08:52
See my [comment](https://github.com/decentralized-identity/universal-resolver/commit/a3a57541482c4bd0b8c6dbe30c748cd581664f05) in the universal resolver repo. The root cause is that the property was removed from the parent pom, without adding it to the pom of this project. A second issue is that the startup script uses the `jetty:run` command which rebuilds the war each time the container starts. I think this makes more sense in a dev environment. I would propose building the war beforehand and then using something like `jetty:start-war`. Like this the build pipeline would break before releasing a unstable version.

**Comment by cihansg** [comment] 2021-04-29 10:15
As @etschelp pointed out, the cause was the removed version property from the parent pom, and c03ccb8d2483191f1e856226207c7350ae71401d should have resolved the issue. @Jsyro I will wait for your confirmation before closing the issue.

@etschelp also, thanks for the information regards to the startup script. We can open another issue for it by referring to the problem you have stated.

**Comment by Jsyro** [comment] 2021-04-29 16:22
That resolved it! Thanks.

**Closed as completed** 2021-04-29 16:33 UTC
